In [2]:
import pandas as pd

## Agrupando dados por ano

### 2018

In [3]:

df_2018 = pd.read_csv('data/2018/beneficios-concedidos-12-2018.csv', sep=';')

df_2018.head()

,Competência concessão,Espécie,CID,CID.1,Despacho,Dt Nascimento,Sexo.,Clientela,Mun Resid,Vínculo dependentes,Forma Filiação,UF,Qt SM RMI
0,2018-12-01,Pensão por Morte Previdenciária,0,Zerados,Concessao Decorrente de Acao Judicial,22/06/2005,Feminino,Urbano,02043-AL-Maceió,Filho,Empregado,Alagoas,"4,326"
1,2018-12-01,Auxílio Salario Maternidade,0,Zerados,Concessao Normal,14/08/1994,Feminino,Rural,03038-AM-São Paulo de Olivença,Filho,Segurado Especial,Amazonas,1
2,2018-12-01,Aposentadoria por Tempo de Contribuição,0,Zerados,Concessao com Conversao Tempo de Servico,09/12/1959,Masculino,Urbano,04307-BA-Simões Filho,Não Informado,Autônomo,Bahia,"1,586"
3,2018-12-01,Auxílio Salario Maternidade,0,Zerados,Concessao Normal,20/08/1981,Feminino,Urbano,04275-BA-Salvador,Filho,Facultativo,Bahia,1
4,2018-12-01,Pensão por Morte Previdenciária,0,Zerados,Concessao Normal,04/01/1956,Feminino,Urbano,04007-BA-Alagoinhas,Cônjuge,Autônomo,Bahia,1

### 2019

In [4]:
df_01_19 = pd.read_csv('data/2019/concedidos-01-2019.csv', sep=';')
df_02_19 = pd.read_csv('data/2019/concedidos-02-2019.csv', sep=';')
df_03_19 = pd.read_csv('data/2019/concedidos-03-2019.csv', sep=';')
df_04_19 = pd.read_csv('data/2019/concedidos-04-2019.csv', sep=';')
df_05_19 = pd.read_csv('data/2019/concedidos-05-2019.csv', sep=';')
df_06_19 = pd.read_csv('data/2019/concedidos-06-2019.csv', sep=';')
df_07_19 = pd.read_csv('data/2019/concedidos-07-2019.csv', sep=';')
df_08_19 = pd.read_csv('data/2019/concedidos-08-2019.csv', sep=';')
df_09_19 = pd.read_csv('data/2019/concedidos-09-2019.csv', sep=';')
df_10_19 = pd.read_csv('data/2019/concedidos-10-2019.csv', sep=';')
df_11_19 = pd.read_csv('data/2019/concedidos-11-2019.csv', sep=';')
df_12_19 = pd.read_csv('data/2019/concedidos-12-2019.csv', sep=';')

df_2019 = pd.concat([df_01_19, df_02_19, df_03_19, df_04_19, df_05_19, df_06_19, df_07_19, df_08_19, df_09_19, df_10_19, df_11_19, df_12_19], ignore_index=True)

df_2019.head()

,Competência concessão,Espécie,CID,CID.1,Despacho,Dt Nascimento,Sexo.,Clientela,Mun Resid,Vínculo dependentes,Forma Filiação,UF,Qt SM RMI
0,janeiro/2019,Auxílio Doenca Previdenciário,I83,I83 Varizes dos Membros Infer,Concessao Normal,25/10/1967,Feminino,Urbano,02003-AL-Arapiraca,Filho,Empregado,Alagoas,"1,068"
1,janeiro/2019,Auxílio Doenca Previdenciário,S525,S52.5 Frat da Extremidade Distal do Radio,Conc. Base Artigo 27 Inciso Ii do Rbps,16/05/1994,Masculino,Urbano,02003-AL-Arapiraca,Não Informado,Empregado,Alagoas,"1,099"
2,janeiro/2019,Auxílio Doenca Previdenciário,N811,N81.1 Cistocele,Concessao Normal,03/03/1967,Feminino,Urbano,02003-AL-Arapiraca,Não Informado,Autônomo,Alagoas,"1,000"
3,janeiro/2019,Auxílio Doenca Previdenciário,O200,O20.0 Ameaca de Aborto,Concessao Normal,06/09/1986,Feminino,Urbano,02003-AL-Arapiraca,Filho,Desempregado,Alagoas,"1,000"
4,janeiro/2019,Auxílio Doenca Previdenciário,K80,K80 Colelitiase,Concessao Normal,23/06/1983,Feminino,Urbano,02003-AL-Arapiraca,Filho,Empregado,Alagoas,"1,728"

### 2020

In [5]:
df_01_20 = pd.read_csv('data/2020/beneficios-concedidos-01-2020.csv', sep=';')
df_02_20 = pd.read_csv('data/2020/beneficios-concedidos-02-2020.csv', sep=';')
df_03_20 = pd.read_csv('data/2020/beneficios-concedidos-03-2020.csv', sep=';')
df_04_20 = pd.read_csv('data/2020/beneficios-concedidos-04-2020.csv', sep=';')
df_05_20 = pd.read_csv('data/2020/beneficios-concedidos-05-2020.csv', sep=';')
df_06_20 = pd.read_csv('data/2020/beneficios-concedidos-06-2020.csv', sep=';')
df_07_20 = pd.read_csv('data/2020/beneficios-concedidos-07-2020.csv', sep=';')
df_08_20 = pd.read_csv('data/2020/beneficios-concedidos-08-2020.csv', sep=';')
df_09_20 = pd.read_csv('data/2020/beneficios-concedidos-09-2020.csv', sep=';')
df_10_20 = pd.read_csv('data/2020/beneficios-concedidos-10-2020.csv', sep=';')
df_11_20 = pd.read_csv('data/2020/beneficios-concedidos-11-2020.csv', sep=';')
df_12_20 = pd.read_csv('data/2020/beneficios-concedidos-12-2020.csv', sep=';')

df_2020 = pd.concat([df_01_20, df_02_20, df_03_20, df_04_20, df_05_20, df_06_20, df_07_20, df_08_20, df_09_20, df_10_20, df_11_20, df_12_20], ignore_index=True)

df_2020.head()

,Competência concessão,Espécie,CID,CID_1,Despacho,Dt Nascimento,Sexo.,Clientela,Mun Resid,Vínculo dependentes,Forma Filiação,UF,Qt SM RMI,"mandar continuar, obrigado."
0,202001.0,Auxílio Salario Maternidade,000000,Zerados,Concessao Normal,25/01/1988,Feminino,Rural,09149-MA-Bom Jesus das Selvas,Filho,Segurado Especial,Alagoas,1,NaN
1,202001.0,Auxílio Doenca por Acidente do Trabalho,S43,S43 Luxacao Entorse Distens Artic Lig Cint,Concessao Normal,07/05/1981,Masculino,Urbano,02075-AL-Porto Real do Colégio,Não Informado,Empregado,Alagoas,1,NaN
2,202001.0,Pensão por Morte Previdenciária,000000,Zerados,Concessao Normal,06/06/1959,Feminino,Rural,22002-SE-Aquidabã,Cônjuge,Segurado Especial,Alagoas,1,NaN
3,202001.0,Pensão por Morte Previdenciária,000000,Zerados,Concessao Normal,25/11/1974,Feminino,Rural,09170-MA-Igarapé do Meio,Cônjuge,Segurado Especial,Alagoas,1,NaN
4,202001.0,Pensão por Morte Previdenciária,000000,Zerados,Concessao Normal,14/09/1999,Feminino,Rural,05002-CE-Acaraú,Filho,Segurado Especial,Alagoas,1,NaN

### 2021

In [6]:
df_01_21 = pd.read_csv('data/2021/beneficios-concedidos-01-2021.csv', sep=';')
df_02_21 = pd.read_csv('data/2021/beneficios-concedidos-02-2021.csv', sep=';')
df_03_21 = pd.read_csv('data/2021/beneficios-concedidos-03-2021.csv', sep=';')
df_04_21 = pd.read_csv('data/2021/beneficios-concedidos-04-2021.csv', sep=';')

# Comparando os dados entre os itens que estão em formatos diferentes
df_05_21_csv = pd.read_csv('data/2021/beneficios-concedidos-05-2021.csv', sep=';')
df_05_21_json = pd.read_json('data/2021/beneficios-concedidos-05-2021.json')
df_05_21_xml = pd.read_xml('data/2021/beneficios-concedidos-05-2021.xml', xpath='/viewrecord/nodes/node', attrs_only=True)

df_05_21_xml.head()

ValueError: xpath does not return any nodes or attributes. Be sure to specify in `xpath` the parent nodes of children and attributes to parse. If document uses namespaces denoted with xmlns, be sure to define namespaces and use them in xpath.

### 2022

### 2023